# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Sobre Mi
    url: /
    weight: 10
  - name: Formación y Experiencia
    url: experience/
    weight: 11
  - name: Formación
    url: /#papers
    weight: 12
  - name: Talks
    url: /#talks
    weight: 13
  - name: News
    url: /#news
    weight: 14

  - name: Projects
    url: projects/
    weight: 30
  - name: Hobbies
    url: teaching/
    weight: 40
